@API_URL = http://127.0.0.1:8000
# @API_URL=http://laravel-rob-demo.herokuapp.com

### HOME
GET {{API_URL}}

### Animals All
GET {{API_URL}}/api/animals

### Animal single
GET {{API_URL}}/api/animals/4


### Animal NEW
POST {{API_URL}}/api/animals
Accept: application/json
Content-Type: application/json

{
  "name": "giraffe",
  "age": "13"
}

### Animal UPDATE
PATCH  {{API_URL}}/api/animals/10
Content-Type: application/json
Accept: application/json

{
  "name": "koa"
}

### Animal DELETE
DELETE {{API_URL}}/api/animals/10
Accept: application/json
