@API_URL = http://127.0.0.1:8000

### HOME
GET {{API_URL}}

### Animals All
GET {{API_URL}}/api/animals

### Animal single
GET {{API_URL}}/api/animals/9


### Animal NEW
POST {{API_URL}}/api/animals
Accept: application/json
Content-Type: application/json

{
  "name": "koalaaa"
}

### Animal UPDATE
PATCH  {{API_URL}}/api/animals/9
Content-Type: application/json
Accept: application/json

{
  "name": "koa"
}

### Animal DELETE
DELETE {{API_URL}}/api/animals/7
Accept: application/json
